name: Build

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'extras/images/**'

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "Linux", os: ubuntu-latest }

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Display OpenSSL version
        run: openssl version

      - name: Upgrade PIP
        run: python3 -m pip install --upgrade pip setuptools wheel

      - name: Display Python version
        run: python3 --version

      - name: Display PIP version
        run: python3 -m pip --version

      - name: Install python dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Test Without Password
        env:
          BTC_WALLET_PRIV: ${{ secrets.BTC_WALLET_PRIV_2 }}
        run: python3 transfer.py --to 1Em2mh42vmqDxHLuaMM2u6KQPJWFDP8Jy8 --amount 0.00000001 --draft

      - name: Test With Password
        env:
          BTC_WALLET_PRIV: ${{ secrets.BTC_WALLET_PRIV_1 }}
          BTC_WALLET_PRIV_PASS: ${{ secrets.BTC_WALLET_PRIV_PASS_1 }}
        run: python3 transfer.py --to 1Em2mh42vmqDxHLuaMM2u6KQPJWFDP8Jy8 --amount 0.00000001 --draft
